--DROP DATABASE choques;
CREATE DATABASE choques;

CREATE SCHEMA raw;

--DROP TABLE IF EXISTS raw.vehicles;
CREATE TABLE raw.vehicles (
	crash_unit_id BIGINT,
	crash_record_id TEXT,
	crash_date TIME,
	unit_no BIGINT,
	unit_type TEXT,
	num_passengers BIGINT,
	vehicle_id BIGINT,
	cmrc_veh_i TEXT,
	make TEXT,
	model TEXT,
	lic_plate_state TEXT,
	vehicle_year BIGINT,
	vehicle_defect TEXT,
	vehicle_type TEXT,
	vehicle_use TEXT,
	travel_direction TEXT,
	maneuver TEXT,
	towed_i TEXT,
	fire_i TEXT,
	occupant_cnt BIGINT,
	exceed_speed_limit_i TEXT,
	towed_by TEXT,
	towed_to TEXT,
	area_00_i TEXT,
	area_01_i TEXT,
	area_02_i TEXT,
	area_03_i TEXT,
	area_04_i TEXT,
	area_05_i TEXT,
	area_06_i TEXT,
	area_07_i TEXT,
	area_08_i TEXT,
	area_09_i TEXT,
	area_10_i TEXT,
	area_11_i TEXT,
	area_12_i TEXT,
	area_99_i TEXT,
	first_contact_point TEXT,
	cmv_id TEXT,
	usdot_no TEXT,
	ccmc_no TEXT,
	ilcc_no TEXT,
	commercial_src TEXT,
	gvwr TEXT,
	carrier_name TEXT,
	carrier_state TEXT,
	carrier_city TEXT,
	hazmat_placards_i TEXT,
	hazmat_name TEXT,
	un_no TEXT,
	hazmat_present_i TEXT,
	hazmat_report_i TEXT,
	hazmat_report_no TEXT,
	mcs_report_i TEXT,
	mcs_report_no TEXT,
	hazmat_vio_cause_crash_i TEXT,
	mcs_vio_cause_crash_i TEXT,
	idot_permit_no TEXT,
	wide_load_i TEXT,
	trailer1_width TEXT,
	trailer2_width TEXT,
	trailer1_length TEXT,
	trailer2_length TEXT,
	total_vehicle_length TEXT,
	axle_cnt TEXT,
	vehicle_config TEXT,
	cargo_body_type TEXT,
	load_type TEXT,
	hazmat_out_of_service_i TEXT,
	mcs_out_of_service_i TEXT,
	hazmat_class TEXT
);

\copy raw.vehicles (crash_unit_id,crash_record_id,crash_date,unit_no,unit_type,num_passengers,vehicle_id,cmrc_veh_i,make,model,lic_plate_state,vehicle_year,vehicle_defect,vehicle_type,vehicle_use,travel_direction,maneuver,towed_i,fire_i,occupant_cnt,exceed_speed_limit_i,towed_by,towed_to,area_00_i,area_01_i,area_02_i,area_03_i,area_04_i,area_05_i,area_06_i,area_07_i,area_08_i,area_09_i,area_10_i,area_11_i,area_12_i,area_99_i,first_contact_point,cmv_id,usdot_no,ccmc_no,ilcc_no,commercial_src,gvwr,carrier_name,carrier_state,carrier_city,hazmat_placards_i,hazmat_name,un_no,hazmat_present_i,hazmat_report_i,hazmat_report_no,mcs_report_i,mcs_report_no,hazmat_vio_cause_crash_i,mcs_vio_cause_crash_i,idot_permit_no,wide_load_i,trailer1_width,trailer2_width,trailer1_length,trailer2_length,total_vehicle_length,axle_cnt,vehicle_config,cargo_body_type,load_type,hazmat_out_of_service_i,mcs_out_of_service_i,hazmat_class) FROM 'D:\Traffic_Crashes_-_Vehicles_20250129.csv'  WITH (FORMAT CSV, HEADER true, DELIMITER ',');
